alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK172ejh3wxi5shji9jiflewbpu;
drop table if exists b2c_requests;
drop table if exists b2c_response;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK172ejh3wxi5shji9jiflewbpu;
drop table if exists b2c_requests;
drop table if exists b2c_response;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK172ejh3wxi5shji9jiflewbpu;
drop table if exists b2c_requests;
drop table if exists b2c_response;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK172ejh3wxi5shji9jiflewbpu;
drop table if exists b2c_requests;
drop table if exists b2c_response;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK172ejh3wxi5shji9jiflewbpu;
drop table if exists b2c_requests;
drop table if exists b2c_response;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK172ejh3wxi5shji9jiflewbpu;
drop table if exists b2c_requests;
drop table if exists b2c_response;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK172ejh3wxi5shji9jiflewbpu;
drop table if exists b2c_requests;
drop table if exists b2c_response;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK172ejh3wxi5shji9jiflewbpu;
drop table if exists b2c_requests;
drop table if exists b2c_response;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK82pl7dtj08n740b7uspnufson;
drop table if exists b2c_requests;
drop table if exists b2c_result;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK82pl7dtj08n740b7uspnufson;
drop table if exists b2c_requests;
drop table if exists b2c_result;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK82pl7dtj08n740b7uspnufson;
drop table if exists b2c_requests;
drop table if exists b2c_result;
drop table if exists b2c_transactions;
alter table if exists b2c_transactions drop foreign key if exists FKt526tud7914r9snvy5ivjjlvd;
alter table if exists b2c_transactions drop foreign key if exists FK82pl7dtj08n740b7uspnufson;
drop table if exists b2c_requests;
drop table if exists b2c_result;
drop table if exists b2c_transactions;
