services:

  payment_api:
    image: openjdk:17
    container_name: tanda_payment_api
    hostname: tanda_payment_api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "6793:6793"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:6793/payment-api/ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tanda_network
    command: "java -jar /payment-api.jar"

  mariadb:
    extends:
      service: mariadb
      file: mariadb/mariadb-docker-compose.yaml
    networks:
      - tanda_network

  zookeeper:
    extends:
      service: zookeeper
      file: kafka/kafka-docker-compose.yaml
    networks:
      - tanda_network

  kafka:
    extends:
      service: kafka
      file: kafka/kafka-docker-compose.yaml
    depends_on:
      - zookeeper
    networks:
      - tanda_network

volumes:
  mariadb_data:
  kafka_data:
  zookeeper_data:

networks:
  tanda_network:
    external: true