server:
  port: 6793

  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    name: payment-api


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  config:
    import:
      - classpath:jpa.yml
      - classpath:kafka.yml

  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: jdbc:${spring.datasource.protocol}://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}

logging:
  level:
    org:
      hibernate:
        sql: error
      springframework:
        kafka: debug
        web: debug
        security: debug
        data:
          mongodb:
            core: debug
debug:
  true
