spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    generate-ddl: true
    show-sql: true
    database-platform: ${spring.datasource.driver-class-name}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        hbm2ddl:
          schema-generation:
            auto: update
            scripts:
              action: create
              create-target: target/schema.sql
              drop-target: target/drop.sql
      javax:
        persistence:
          jdbc:
            url: "${spring.datasource.url}"
            driver: "${spring.datasource.driver-class-name}"
            user: "${spring.datasource.username}"
            password: "${spring.datasource.password}"
          schema-generation:
            database:
              action: drop-and-create
            scripts:
              action: ${spring.jpa.hibernate.ddl-auto}
              create-target: payment-api-schema.sql
              drop-target: drop-payment-api-schema.sql