package com.tanda.payment_api.globals;

public class GlobalVariables {
    public static final Integer MAX_RETRY_COUNT = 3;
    public static final String GW_RESPONSE_KAFKA_TEMPLATE = "gwResponseKafkaTemplate";
    public static final String QUEUE_TIME_OUT_URL = "QueueTimeOutURL";
    public static final String REMARKS = "Remarks";
    public static final String OCCASSION = "Occassion";
    public static final String PARTY_A = "PartyA";
    public static final String PARTY_B = "PartyB";
    public static final String AMOUNT = "Amount";
    public static final String COMMAND_ID = "CommandID";
    public static final String RESPONSE_DESCRIPTION = "ResponseDescription";
    public static final String RESPONSE_CODE = "ResponseCode";
    public static final String CONVERSATION_ID = "ConversationID";
    public static final String ORIGINATOR_CONVERSATION_ID = "OriginatorConversationID";
    public static final String KAFKA_GW_GROUP_ID = "gw_payment";
    public static final String KAFKA_GW_REQUEST_CONTAINER_FACTORY = "gwRequestKafkaContainerFactory";
    public static final String KAFKA_GW_REQUEST_TOPIC = "gw_request";
    public static final String KAFKA_GW_RESPONSE_TOPIC = "gw_response";
    public static final String RESULT = "Result";
    public static final String RESULT_URL = RESULT + "URL";
    public static final String RESULT_TYPE = RESULT + "Type";
    public static final String RESULT_DESC = RESULT + "Desc";
    public static final String RESULT_CODE = RESULT + "Code";
    public static final String RESULT_PARAMETER = RESULT + "Parameter";
    public static final String RESULT_PARAMETERS = RESULT_PARAMETER + "s";
    public static final String REFERENCE_DATA = "ReferenceData";
    public static final String REFERENCE_ITEM = "ReferenceItem";
    public static final String SECURITY_CREDENTIALS = "SecurityCredential";
    public static final String _REQUIRED = "_required";
    public static final String INITIATOR_NAME = "InitiatorName";
    public static final String TRANSACTION_ID = "TransactionID";
    public static final String TRANSACTION_AMOUNT = "TransactionAmount";
    public static final String TRANSACTION_RECEIPT = "TransactionReceipt";
    public static final String B2C_RECIPIENT_IS_REGISTERED_CUSTOMER = "B2CRecipientIsRegisteredCustomer";
    public static final String B2C_CHARGES_PAID_ACCOUNT_AVAILABLE_FUNDS = "B2CChargesPaidAccountAvailableFunds";
    public static final String RECEIVER_PARTY_PUBLIC_NAME = "ReceiverPartyPublicName";
    public static final String TRANSACTION_COMPLETED_DATE_TIME = "TransactionCompletedDateTime";
    public static final String TRANSACTION_COMPLETED_DATE_TIME_DATE_FORMAT = "dd.MM.yyyy HH:mm:ss";
    public static final String B2C_UTILITY_ACCOUNT_AVAILABLE_FUNDS = "B2CUtilityAccountAvailableFunds";
    public static final String B2C_WORKING_ACCOUNT_AVAILABLE_FUNDS = "B2CWorkingAccountAvailableFunds";
}
