services:

  zookeeper:
    container_name: payment_zookeeper
    hostname: zookeeper
    restart: unless-stopped
    image: confluentinc/cp-zookeeper:7.4.4
    ports:
      - "2181:2181"
    env_file:
      - .env
    volumes:
      - zookeeper_data:/var/lib/zookeeper
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tanda_network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: payment_kafka
    hostname: kafka
    restart: unless-stopped

    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    depends_on:
      zookeeper:
        condition: service_healthy
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "sh", "-c", "kafka-topics --bootstrap-server=kafka:9092 --list" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tanda_network

volumes:

  zookeeper_data:
    driver: local

  kafka_data:
    driver: local

